// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oatjauerfxwykzihases.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hdGphdWVyZnh3eWt6aWhhc2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjE0MTEsImV4cCI6MjA2MzkzNzQxMX0.L4M6fq2gO7m1uFwgtFUGqcKFBxUfKI2megRNyyIZQ4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);